export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  SIGNUP: '/signup',
  SERVICES: '/services',
  SERVICE_DETAILS: '/listing/:id',
  PROFILE: '/profile',
  BOOKINGS: '/bookings',
  BOOKING_DETAILS: '/booking/:id',
  ABOUT: '/about',
  CONTACT: '/contact',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password/:token',
  
  // Provider routes
  PROVIDER_DASHBOARD: '/provider/dashboard',
  PROVIDER_CREATE_LISTING: '/provider/create-listing',
  PROVIDER_EDIT_LISTING: '/provider/edit-listing/:id',
  PROVIDER_PROFILE: '/provider/profile',
  PROVIDER_PROFILE_ID: '/provider/profile/:id',
  PROVIDER_BOOKINGS: '/provider/bookings',
  PROVIDER_SERVICES: '/provider/services',
  PROVIDER_EDIT_SERVICE: '/provider/services/edit/:serviceId',
  PROVIDER_ADD_SERVICE: '/provider/services/new',
  
  // Admin routes
  ADMIN_DASHBOARD: '/admin',
  ADMIN_USERS: '/admin/users',
  ADMIN_USERS_CREATE: '/admin/users/create',
  ADMIN_PROVIDERS: '/admin/providers',
  ADMIN_LISTINGS: '/admin/listings',
  ADMIN_BOOKINGS: '/admin/bookings',
  ADMIN_CATEGORIES: '/admin/categories',
  ADMIN_COMMISSIONS: '/admin/commissions',
  ADMIN_COMPLAINTS: '/admin/complaints',
  ADMIN_REPORTS: '/admin/reports',
  ADMIN_SETTINGS: '/admin/settings',
  ADMIN_PROFILE: '/admin/profile',
};